import Header from '@/app/components/Header';
import { numans } from '@/app/ui/fonts';
import '@/app/ui/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata = {
	title: 'Marc VILLEVIEILLE - Développeur Front-End',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body
				className={`${numans.className} m-auto box-border bg-neutral-100 text-mauve-text antialiased`}
			>
				<div className="m-auto box-border min-h-screen">
					<Header />
					<main>{children}</main>
					{/* <Footer /> */}
				</div>
			</body>
		</html>
	);
}
